In [1]:
import numpy as np
def computeVectorLength(vector):
  len_of_vector = np.linalg.norm(vector)

  return len_of_vector

In [ ]:
vector = np.array([-2, 4, 9, 21])
result = computeVectorLength([vector])
print(round(result,2))

23.28


In [ ]:
def computeDotProduct(vector1, vector2):
  result = np.dot(vector1, vector2)

  return result

In [ ]:
v1 = np.array([0, 1, -1, 2])
v2 = np.array([2, 5, 1, 0])
result = computeDotProduct(v1, v2)

print(round(result,2))

4


In [ ]:
x = np.array([[1, 2],
              [3, 4]])
k = np.array([1, 2])
print('result  \n', computeDotProduct(x, k))
print('result 1 \n', x.dot(k))

result  
 [ 5 11]
result 1 
 [ 5 11]


In [ ]:
x = np.array([[-1, 2],
              [3, -4]])
k = np.array([1, 2])
print('result \n', x@k)

result 
 [ 3 -5]


In [ ]:
def matrix_multi_vector(matrix, vector):
  result = np.dot(matrix, vector)
  return result

In [ ]:
m = np.array([[-1, 1, 1], [0, -4, 9]])
v = np.array([0, 2, 1])
result = matrix_multi_vector(m, v)
print(result)

[3 1]


In [ ]:
def matrix_multi_matrix(matrix1, matrix2):
  result = np.dot(matrix1, matrix2)
  return result

In [ ]:
m1 = np.array([[0, 1, 2], [2, -3, 1]])
m2 = np.array([[1, -3],[6, 1], [0, -1]])
result = matrix_multi_matrix(m1, m2)
print(result)

[[  6  -1]
 [-16 -10]]


In [ ]:
m1 = np.eye(3)
m2 = np.array([[1, 1, 1],[2, 2, 2], [3, 3, 3]])
result = m1@m2
print(result)

[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [ ]:
m1 = np.eye(2)
m1 = np.reshape(m1,(-1,4))[0]
m2 = np.array([[1, 1, 1, 1],[2, 2, 2, 2], [3, 3, 3, 3], [4, 4, 4, 4]])
result = m1@m2
print(result)

[5. 5. 5. 5.]


In [ ]:
m1 = np.array([[1, 2], [3, 4]])
m1 = np.reshape(m1,(-1,4), "F")[0]
m2 = np.array([[1, 1, 1, 1],[2, 2, 2, 2], [3, 3, 3, 3], [4, 4, 4, 4]])
result = m1@m2
print(result)

[29 29 29 29]


In [ ]:
def inverse_matrix(matrix):
  result = np.linalg.inv(matrix)
  return result

In [ ]:
m1 = np.array([[-2, 6], [8, -4]])
result = inverse_matrix(m1)
print(result)

[[0.1  0.15]
 [0.2  0.05]]


In [2]:
def compute_eigenvalues_eigenvectors(matrix):
  eigenvalues, eigenvectors = np.linalg.eig(matrix)
  return eigenvalues,eigenvectors

In [3]:
matrix = np.array([[1, 4], [3, 2]])
eigenvalues, eigenvectors = compute_eigenvalues_eigenvectors(matrix)
print(eigenvectors)

[[-0.8        -0.70710678]
 [ 0.6        -0.70710678]]


In [ ]:
import numpy as np
from numpy import dot
from numpy.linalg import norm

def compute_cosine(v1, v2):
  cos_sim = computeDotProduct(v1,v2) / (computeVectorLength(v1)*computeVectorLength(v2))

  return cos_sim

In [ ]:
x = np.array([1, 2, 3, 4])
y = np.array([1, 0, 3, 0])
result = compute_cosine(x,y)
print(round(result, 3))

0.577
