In [1]:
import sklearn
from sklearn.neighbors import KNeighborsClassifier
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np

In [2]:
vectorizer = CountVectorizer()
corpus = ["góp gió gặt bão",
          "có làm mới có ăn",
          "đất lành chim đậu",
          "ăn cháo đá bát",
          "gậy ông đập lưng ông",
          "qua cầu rút ván"]
X = vectorizer.fit_transform(corpus)

In [7]:
X = X.toarray()
print(X)

[[0 1 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1]
 [1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 2 0 0 0 1 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0]]


In [4]:
x_test = vectorizer.transform(['không làm cạp đất mà ăn']).toarray()
x_test

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
        0]])

In [5]:
y_data = np.array([1, 1, 1, 0, 0, 0])
y_data

array([1, 1, 1, 0, 0, 0])

### Step-by-step

In [10]:
# 1. compute distances
distances = np.sqrt( ((X-x_test)**2).sum(axis=1) )
print(distances)

[2.64575131 2.44948974 2.23606798 2.23606798 3.16227766 2.64575131]


In [11]:
# 2. get the top k
top_k = np.argsort(distances)
print(top_k)

k = 3
top_k = top_k[:k]
print(top_k)

[2 3 1 0 5 4]
[2 3 1]


## sklearn

In [8]:
from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier(n_neighbors=6)
classifier.fit(X, y_data)

y_pred = classifier.kneighbors(x_test)
print(y_pred)

(array([[2.23606798, 2.23606798, 2.44948974, 2.64575131, 2.64575131,
        3.16227766]]), array([[2, 3, 1, 0, 5, 4]]))
