### Phép toán trên mảng(Array Math)

In [ ]:
# aivietnam.ai
import numpy as np

x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

print('data x \n', x)
print('data y \n', y)

# Tổng của 2 mảng
print('method 1 \n', x + y)
print('method 2 \n', np.add(x, y))

In [ ]:
# aivietnam.ai
import numpy as np

x = np.array([5,6,7,8])
y = np.array([1,2,3,4])

print('data x \n', x)
print('data y \n', y)

# Hiệu 2 mảng
print('method 1 \n', x - y)
print('method 2 \n', np.subtract(x, y))

In [ ]:
# aivietnam.ai
import numpy as np

x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

print('data x \n', x)
print('data y \n', y)

# Tích các phần tử tương ứng giữa x và y
print('method 1 \n', x*y)
print('method 2 \n', np.multiply(x, y))

In [ ]:
# aivietnam.ai
import numpy as np

x = np.array([5,6,7,8])
y = np.array([1,2,3,4])

print('data x \n', x)
print('data y \n', y)

# Phép chia các từng phần tương ứng x cho y
print('method 1 \n', x / y)
print('method 2 \n', x // y)
print('method 3 \n', np.divide(x, y))

In [ ]:
# aivietnam.ai
import numpy as np

data = np.array([1,2,3,4])

print('data \n', data)

# Căn bậc 2 từng phần tử trong data
print('sqrt \n', np.sqrt(data))

In [ ]:
# aivietnam.ai
import numpy as np

v = np.array([1, 2])
w = np.array([2, 3])

# Tính inner product giữa v và w
print('method 1 \n', v.T.dot(w))
print('method 2 \n', np.dot(v, w))

In [1]:
# aivietnam.ai
import numpy as np

v = np.array([1, 2])
w = np.array([2, 3])

# Tính inner product giữa v và w
print('method 1 \n', v.dot(w))
print('method 2 \n', np.dot(v, w))

method 1 
 8
method 2 
 8


In [1]:
# aivietnam.ai
import numpy as np

X = np.array([[1,2],[4,3]])
v = np.array([1,2])

print('\n matrix X \n', X)
print('\n vector v \n', v)

# phép nhân giữa ma trận và vector
print('\n method 1: X.dot(v) \n', X.dot(v))
print('\n method 1: v.dot(X) \n', v.dot(X))
print('\n method 2: X.dot(v) \n', np.dot(X, v))
print('\n method 2: v.dot(X) \n', np.dot(v, X))


 matrix X 
 [[1 2]
 [4 3]]

 vector v 
 [1 2]

 method 1: X.dot(v) 
 [ 5 10]

 method 1: v.dot(X) 
 [9 8]

 method 2: X.dot(v) 
 [ 5 10]

 method 2: v.dot(X) 
 [9 8]


In [ ]:
# aivietnam.ai
import numpy as np

X = np.array([[1,2],[4,3]])
Y = np.array([[2,3],[2,1]])

print(' matrix X \n', X)
print('\n matrix Y \n', Y)

# Phép nhân giữa hai ma trận
print('\n method 1 \n', X.dot(Y))
print('\n method 2 \n', np.dot(X, Y))

### sum

In [2]:
# aivietnam.ai
import numpy as np

X = np.array([[1,2],
              [3,4]])

# Tổng các phần tử của mảng
print(np.sum(X))  

 # Tính tổng theo từng cột
print(np.sum(X, axis=0))

# Tính tổng theo từng dòng
print(np.sum(X, axis=1))  

10
[4 6]
[3 7]


In [1]:
# aivietnam.ai
import numpy as np

X = np.array([[1,2], 
              [3,4]])
print(X) 

#chuyển vị
print(X.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


### argmin and argmax

In [1]:
import numpy as np

x = np.array([4, 7, 1, 5])
result = np.argmin(x)
print(result)

2


In [2]:
import numpy as np

x = np.array([4, 7, 1, 5])
result = np.argmax(x)
print(result)

1


### min and max

In [3]:
import numpy as np

x = np.array([4, 7, 1, 5])
result = np.min(x)
print(result)

1


In [4]:
import numpy as np

x = np.array([4, 7, 1, 5])
result = np.max(x)
print(result)

7


### sum and average

In [5]:
import numpy as np

x = np.array([6, 5, 7, 1, 9, 2])
result = np.sum(x)
print(result)

30


In [6]:
import numpy as np

x = np.array([6, 5, 7, 1, 9, 2])
result = np.mean(x)
print(result)

5.0
