In [1]:
import numpy as np

u = np.array([3, 2, 4, 1])
v = np.array([2, 1, 0, 3])

r = np.einsum('i,i->', u, v)
print(r)

11


In [2]:
import numpy as np

u = np.array([3, 2, 4, 1])
v = np.array([2, 1, 0, 3])

r = np.einsum('i,j->i', u, v)
print(r)

[18 12 24  6]


In [3]:
import numpy as np

u = np.array([3, 2, 4, 1])
v = np.array([2, 1, 0, 3])

r = np.einsum('i,j->j', u, v)
print(r)

[20 10  0 30]


In [4]:
import numpy as np

u = np.array([3, 2, 4, 1])
v = np.array([2, 1, 0, 3])

r = np.einsum('i,j->ij', u, v)
print(r)

[[ 6  3  0  9]
 [ 4  2  0  6]
 [ 8  4  0 12]
 [ 2  1  0  3]]


In [5]:
import numpy as np

A = np.array([[0, 2, 1],
              [3, 1, 4]])
T = np.einsum('ij->ji', A)
print(T)

[[0 3]
 [2 1]
 [1 4]]


In [6]:
import numpy as np

A = np.array([[5, 2, 1],
                  [3, 1, 6],
                  [2, 4, 3]])
r = np.einsum('ii->i', A)
print(r)

[5 1 3]


In [7]:
import numpy as np

A = np.array([[5, 2, 1],
              [3, 1, 6],
              [2, 4, 3]])
r = np.einsum('ii->', A)
print(r)

9


In [8]:
import numpy as np

A = np.array([[3, 0, 1],
              [2, 2, 3]])
B = np.array([[1, 0, 2],
              [3, 2, 1]])
r = np.einsum('ij,ij->ij', A, B)
print(r)

[[3 0 2]
 [6 4 3]]


In [9]:
import numpy as np

A = np.array([[0, 2, 1],
              [3, 1, 4]])
B = np.array([[2, 5],
              [0, 1],
              [3, 4]])
C = np.einsum('ij,jk->ik', A, B)
print(C)

[[ 3  6]
 [18 32]]
