In [2]:
import numpy as np
import pandas as pd

In [3]:
data = pd.read_csv('iris_1D.csv')
data

,Petal_Length,Label
0,1.4,0.0
1,1.0,0.0
2,1.5,0.0
3,3.1,1.0
4,3.8,1.0
5,4.1,1.0


In [4]:
# get x
x_data = data['Petal_Length'].to_numpy()
x_data = x_data.reshape(6, 1)
print(x_data)

[[1.4]
 [1. ]
 [1.5]
 [3.1]
 [3.8]
 [4.1]]


In [6]:
# get y
labels = data['Label'].to_numpy()
print(labels)

[0. 0. 0. 1. 1. 1.]


In [13]:
# unknown input
x_test = [[1.6]]

In [14]:
distances = np.abs(x_data - x_test).sum(axis=1)
print(distances)

argmin = np.argmin(distances)
print(argmin, labels[argmin])

[0.2 0.6 0.1 1.5 2.2 2.5]
2 0.0
