### example 1

In [ ]:
import numpy as np

A = np.array([[108.55, 20.3],
              [20.3, 4.]])
A_inversed = np.linalg.inv(A)

print(A)
print(A_inversed)

In [ ]:
# check
np.set_printoptions(suppress=True)

print(A.dot(A_inversed))
print(A_inversed.dot(A))

### example 2

In [ ]:
import numpy as np

A = np.array([[1, 2],
              [4, 6]])
A_inversed = np.linalg.inv(A)

print(A)
print(A_inversed)

In [ ]:
# check
print(A.dot(A_inversed))
print(A_inversed.dot(A))

In [1]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])
A_inversed = np.linalg.inv(A)

print(A)
print(A_inversed)

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [2]:
print(A.dot(A_inversed))

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [3]:
print(A_inversed.dot(A))

[[1.00000000e+00 0.00000000e+00]
 [1.11022302e-16 1.00000000e+00]]


### example 3

In [4]:
import numpy as np

A = np.array([[1, 0, 4],
              [0, 1, 2],
              [0, -3, -4]])
A_inversed = np.linalg.inv(A)

print(A)
print(A_inversed)

[[ 1  0  4]
 [ 0  1  2]
 [ 0 -3 -4]]
[[ 1.  -6.  -2. ]
 [-0.  -2.  -1. ]
 [ 0.   1.5  0.5]]


In [5]:
# check
print(A.dot(A_inversed))
print(A_inversed.dot(A))

[[ 1.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  1.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00 -8.8817842e-16  1.0000000e+00]]
[[ 1.00000000e+00 -4.44089210e-16  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.11022302e-16  1.00000000e+00]]
