## pytorch

In [1]:
import torch
import numpy as np

 # Image Example
N, C, H, W = 1, 1, 2, 2
data =  np.array([[[5., 1.],
                   [2., 8.]]])
data = data.reshape(N, C, H, W)

input = torch.tensor(data,dtype=torch.float)
layer_norm = torch.nn.LayerNorm([C, H, W])
output = layer_norm(input)
output

tensor([[[[ 0.3651, -1.0954],
          [-0.7303,  1.4606]]]], grad_fn=<NativeLayerNormBackward0>)

In [3]:
import torch
import numpy as np

 # Image Example
N, L, E = 1, 2, 3
data =  np.array([[[1., 1., 1],
                   [2., 8., 1]]])
data = data.reshape(N, L, E)
print(data[0,0,:])
print(data[0,1,:])

input = torch.tensor(data,dtype=torch.float)
layer_norm = torch.nn.LayerNorm(E)
output = layer_norm(input)
print(output)

[1. 1. 1.]
[2. 8. 1.]
tensor([[[ 0.0000,  0.0000,  0.0000],
         [-0.5392,  1.4018, -0.8627]]], grad_fn=<NativeLayerNormBackward0>)


## self-implementation

In [7]:
import numpy as np

data =  np.array([[[5., 1.],
                   [2., 8.]]])
data = data.reshape(1, 2, 2, 1)

eps = 0.0 #1e-5

mean = data.mean(axis=(1, 2, 3))
std  = np.sqrt(data.var(axis=(1, 2, 3)) + eps)

print(mean)
print(std)

output_1 = (data[0] - mean[0]) / std[0]
print('1: \n', output_1[:,:,0])

[4.]
[2.73861279]
1: 
 [[ 0.36514837 -1.09544512]
 [-0.73029674  1.46059349]]
