## Create a tensor

In [1]:
# From a list
import torch

data = [1, 2, 3]
data = torch.tensor(data)
print(data)

tensor([1, 2, 3])


In [2]:
# From a NumPy Array
import numpy as np

data = np.array([1, 2, 3])
data = torch.from_numpy(data)
print(data)

tensor([1, 2, 3])


In [3]:
# Create and set all its elements zeros
import torch

# Create a 3x3 tensor filled with zeros
data = torch.zeros(3, 3)  
print(data)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [4]:
# Create and set all its elements ones
import torch

# Create a 3x3 tensor filled with ones
data = torch.ones(3, 3)  
print(data)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [5]:
# Create and set all its elements some value
import torch

# Create a 3x3 tensor filled with the number 9
data = torch.full((3, 3), 9)  
print(data)

tensor([[9, 9, 9],
        [9, 9, 9],
        [9, 9, 9]])


In [6]:
# Create an identity matrix
import torch

# Creates a 3x3 identity matrix
data = torch.eye(3)  
print(data)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [7]:
# Using the arange function
import torch

# Creates a tensor [0, 1, 2, 3, 4]
data = torch.arange(start=0, end=5, step=1)  
print(data)

tensor([0, 1, 2, 3, 4])


In [8]:
# random uniform
import torch

# Creates a 3x3 tensor with 
# random values between 0 and 1
data = torch.rand(3, 3)
print(data)

tensor([[0.4485, 0.6937, 0.0298],
        [0.1842, 0.9399, 0.0306],
        [0.7499, 0.9779, 0.8464]])


In [9]:
# random integers
import torch

# Creates a 3x3 tensor with random integers between 0 and 4
data = torch.randint(low=0, high=5, size=(3, 3))
print(data)

tensor([[4, 3, 4],
        [2, 3, 3],
        [2, 1, 2]])


In [10]:
# random normal
import torch

# Creates a 3x3 tensor with values 
# sampled from a standard normal distribution
data = torch.randn(3, 3)
print(data)

tensor([[-0.5516,  0.7130, -0.1408],
        [-1.2374,  0.7331, -0.4759],
        [-0.5284,  0.1498, -0.0088]])


In [11]:
# broadcasting
import numpy as np

# create a tensor
tensor1 = torch.tensor([[1, 2], 
                        [3, 4]])
tensor2 = torch.tensor([1])
print(f'Tensor1:\n {tensor1}')
print(f'Tensor2:\n {tensor2}')

# Addition between two tensors
tensor3 = tensor1 + tensor2
print(f'Tensor3:\n {tensor3}')

Tensor1:
 tensor([[1, 2],
        [3, 4]])
Tensor2:
 tensor([1])
Tensor3:
 tensor([[2, 3],
        [4, 5]])


In [12]:
# broadcasting
import numpy as np

# create a tensor
tensor1 = torch.tensor([[1, 2], 
                        [3, 4]])
print(f'Tensor1:\n {tensor1}')

# Between a tensor and a number
tensor2 = tensor1 + 2
print(f'Tensor2:\n {tensor2}')

Tensor1:
 tensor([[1, 2],
        [3, 4]])
Tensor2:
 tensor([[3, 4],
        [5, 6]])


In [13]:
# Compute squared difference
import torch

# Create two tensors
x = torch.tensor([1.0, 2.0, 3.0, 4.0])
y = 5

# Compute squared difference
squared_diff = (x - y) ** 2

print(f'x:\n {x}')
print(f'y = {y}')
print(f'squared_diff:\n {squared_diff}')

x:
 tensor([1., 2., 3., 4.])
y = 5
squared_diff:
 tensor([16.,  9.,  4.,  1.])


In [14]:
# Compute squared difference
import torch

# Create two tensors
x = torch.tensor([1.0, 2.0, 3.0, 4.0])
y = torch.tensor([5.0, 5.0, 5.0, 5.0])

# Compute squared difference
loss_fn = torch.nn.MSELoss()
mse = loss_fn(x,y)

print(f'x:\n {x}')
print(f'y = {y}')
print(f'mse:\n {mse}')

x:
 tensor([1., 2., 3., 4.])
y = tensor([5., 5., 5., 5.])
mse:
 7.5


In [15]:
# Concatenate tensors
import torch

# Create two tensors
x = torch.tensor([[1, 2], 
                  [3, 4]])
y = torch.tensor([[3, 4], 
                  [5, 6]])

# Concat tensors along the first dim
tensor1 = torch.cat((x, y), dim=0)
print(f'Tensor1:\n {tensor1}')

# Concat tensors along the second dim
tensor2 = torch.cat((x, y), dim=1)
print(f'Tensor2:\n {tensor2}')

Tensor1:
 tensor([[1, 2],
        [3, 4],
        [3, 4],
        [5, 6]])
Tensor2:
 tensor([[1, 2, 3, 4],
        [3, 4, 5, 6]])


In [16]:
# argmax
import torch

# Creates a 3x2 tensor
data = torch.randint(low=0, high=9, size=(3, 2))
print(f'data:\n {data}')

# Compute argmax across the rows (dimension 0)
argmax_dim0 = torch.argmax(data, dim=0)
print(f'argmax1:\n {argmax_dim0}')

# Compute argmax across the columns (dimension 1)
argmax_dim1 = torch.argmax(data, dim=1)
print(f'argmax1:\n {argmax_dim1}')

data:
 tensor([[1, 7],
        [8, 3],
        [4, 6]])
argmax1:
 tensor([1, 0])
argmax1:
 tensor([1, 0, 1])


In [17]:
# autograd
import torch

# Create a tensor to compute gradients
x = torch.tensor(2.0, requires_grad=True)

# operation
y = x ** 2
z = 3*y + 2
print(f'z: {z}')

# Backpropagate to compute gradients
z.backward()

# Print the gradient. dz/dx at x=2.0
print(f"Gradient of z w.r.t. x: {x.grad}")

z: 14.0
Gradient of z w.r.t. x: 12.0
