### Example 1: Simple operations

In [3]:
def f_function(number):
    result = number**2 + 1
    return result

def f_function_list(numbers):
    result = []
    for n in numbers:
        result.append(f_function(n))
    return result

# test
numbers = [1, 2, 3, 4]
print(f_function_list(numbers))

[2, 5, 10, 17]


In [7]:
import numpy as np

def f_function(number):
    result = number**2 + 1
    return result

factorial_np = np.vectorize(f_function)

# test
numbers = [1, 2, 3, 4]
numbers_array = np.array(numbers)
print(factorial_np(numbers_array))

[ 2  5 10 17]


In [8]:
import numpy as np

# data
numbers = [1, 2, 3, 4]
numbers_np = np.array(numbers)

# compute
numbers_np = numbers_np**2 + 1
print(numbers_np)

[ 2  5 10 17]


### Compute factorial for a list

In [5]:
def factorial(number):
    result = 1
    for i in range(2, number + 1):
        result *= i
    return result

def factorial_list(numbers):
    result = []
    for n in numbers:
        result.append(factorial(n))
    return result

# test
numbers = [1, 2, 3, 4]
print(factorial_list(numbers))

[1, 2, 6, 24]


### Using numpy

In [1]:
import numpy as np

def factorial(number):
    result = 1
    for i in range(2, number + 1):
        result *= i
    return result

vectorized_factorial = np.vectorize(factorial)

# test
numbers = [1, 2, 3, 4]
numbers_array = np.array(numbers)
print(vectorized_factorial(numbers_array))

[ 1  2  6 24]


In [ ]:
import numpy as np

def factorial(number):
    result = 1
    for i in range(2, number + 1):
        result *= i
    return result

vectorized_factorial = np.vectorize(factorial)

# test
numbers = [1, 2, 3, 4]
numbers_array = np.array(numbers)
print(vectorized_factorial(numbers_array))

In [2]:
import numpy as np

def numpy_factorial(numbers):
    # Create an array of ones with the same shape as the input
    result = np.ones_like(numbers, dtype=np.int64)
    
    # Iterate over each number in the input array
    for i in range(2, np.max(numbers) + 1):
        # Multiply result by i where numbers >= i
        result *= np.where(numbers >= i, i, 1)
    
    return result

# test
numbers = [1, 2, 3, 4]
numbers_array = np.array(numbers)
print(numpy_factorial(numbers_array))

[ 1  2  6 24]
