In [1]:
# aivietnam.ai
# tạo ndarray từ list

import numpy as np

# tạo list 
l = list(range(1, 4))

# tạo ndarray
data = np.array(l)

print(data)
print(data[0])
print(data[1])

[1 2 3]
1
2


In [2]:
# aivietnam.ai
# tạo ndarray từ list

import numpy as np

# tạo ndarray
data1 = np.array([1,2,3])
print(data1.dtype)

data2 = np.array([1.,2.,3.])
print(data2.dtype)

data3 = np.array([1,2,3], dtype=np.int64)
print(data3.dtype)

int32
float64
int64


In [3]:
# aivietnam.ai
# tạo ndarray từ list

import numpy as np

# tạo list 
list1D = [1,2,3]

# tạo ndarray
data = np.array(list1D)

print(data)
print(data.shape)

[1 2 3]
(3,)


In [4]:
# aivietnam.ai
# tạo ndarray từ list

import numpy as np

# tạo list 
list2D = [[1,2],[3,4],[5,6]]

# tạo ndarray
data = np.array(list2D)

print(data)
print(data.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [5]:
# aivietnam.ai
import numpy as np

# tạo list 
l = [[1,2,3],
     [4,5,6]]

# tạo ndarray
data = np.array(l)
print('data\n', data)
print('data shape\n', data.shape)

# reshape
data_rs = np.reshape(data, (3,2))
print('data_rs\n', data_rs)
print('data_rs shape\n', data_rs.shape)

data
 [[1 2 3]
 [4 5 6]]
data shape
 (2, 3)
data_rs
 [[1 2]
 [3 4]
 [5 6]]
data_rs shape
 (3, 2)


In [6]:
# aivietnam.ai
# tạo ndarray từ list

import numpy as np

# tạo list 
list3D = [[[1,6], [2,2], [3,4]],
          [[4,7], [5,2], [6,9]],
          [[7,7], [8,2], [9,5]]]

# tạo ndarray
data = np.array(list3D)

#print(data)
print(data.shape)

(3, 3, 2)


In [7]:
# aivietnam.ai
# tạo ndarray từ list

import numpy as np

# tạo list 
l = list(range(1, 4))

# tạo ndarray
data = np.array(l)

print(data)
print(data.dtype)
print(data.shape)
print(data.ndim)

[1 2 3]
int32
(3,)
1


In [8]:
# aivietnam.ai
# tạo ndarray từ list

import numpy as np

# tạo list 
l = list(range(1, 4))

# tạo ndarray
data = np.array([l,l])

print(data)
print(data.dtype)
print(data.shape)
print(data.ndim)

[[1 2 3]
 [1 2 3]]
int32
(2, 3)
2


In [9]:
# aivietnam.ai
# tạo ndarray từ list

import numpy as np

# tạo list 
l = list(range(1, 4))

# tạo ndarray
data = np.array([l,l])

print(data)
print(type(data))
print(type(data[0]))
print(type(data.shape))
print(type(data.ndim))
print(data.shape)
print(data.ndim)

[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'tuple'>
<class 'int'>
(2, 3)
2


In [10]:
# aivietnam.ai
# thay đổi giá trị phần tử

import numpy as np

# tạo list 
l = list(range(1, 4))

# tạo ndarray
data = np.array(l)
print(data)

data[0] = 8
print(data)

[1 2 3]
[8 2 3]


In [11]:
# aivietnam.ai
# thay đổi giá trị phần tử

import numpy as np

# tạo list 
l = list(range(1, 4))

# tạo ndarray
data = np.array(l)
print(data)

data[0] = 8
print(data)
print(l)

[1 2 3]
[8 2 3]
[1, 2, 3]


### Numpy hàm khởi tạo mảng

In [12]:
# aivietnam.ai
# Tạo một numpy array 
# với tất cả phẩn tử là 0

import numpy as np

# shape: 2 dòng, 3 cột
arr = np.zeros((2,3))  
print(arr)  

[[0. 0. 0.]
 [0. 0. 0.]]


In [13]:
# aivietnam.ai
# Tạo một numpy array với 
# tất cả phẩn tử là 1

import numpy as np

# numpy.ones(shape)
# shape: 2 dòng, 3 cột
arr = np.ones((2,3))  
print(arr)  

[[1. 1. 1.]
 [1. 1. 1.]]


In [14]:
# aivietnam.ai
# Tạo một numpy array với tất 
# cả phẩn tử là hằng số fill_value

import numpy as np

# numpy.full(shape, fill_value)
# shape: 2 dòng, 3 cột
arr = np.full((2,3), 9)  
print(arr)  

[[9 9 9]
 [9 9 9]]


In [15]:
# aivietnam.ai
# Tạo một numpy array với đường chéo là số 1
# số 0 được điền vào những ô phần tử còn lại

import numpy as np

# numpy.eye(N)
# shape: 3 dòng, 3 cột
arr = np.eye(3)  
print(arr)  

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
# aivietnam.ai
# Tạo một numpy array với 
# giá trị ngẫu nhiên

import numpy as np

# np.random.random(size)
# shape: 2 dòng, 3 cột; với 
# phần tử có giá trị ngẫu nhiên
arr = np.random.random((2,3))  
print(arr)

[[0.10967801 0.84028221 0.60813421]
 [0.70996553 0.34230144 0.92027013]]


In [17]:
# aivietnam.ai
import numpy as np

arr = np.array([[1,2], [3,4]])
out = arr.flatten()

print(arr)
print(out)

[[1 2]
 [3 4]]
[1 2 3 4]


In [18]:
# aivietnam.ai
import numpy as np

# create an array
arr = np.arange(5)
print(arr)

# condition
condition = arr < 3
out = np.where(condition, arr, arr*2)

print(condition)
print(out)

[0 1 2 3 4]
[ True  True  True False False]
[0 1 2 6 8]


In [19]:
# aivietnam.ai
import numpy as np

# np.arange(start=0, stop, step=1)
arr1 = np.arange(5)
print(arr1)

arr2 = np.arange(0, 5, 2)
print(arr2)

[0 1 2 3 4]
[0 2 4]


### Array indexing

Numpy cung cấp một số cách để truy xuất phần tử trong mảng
Slicing: Tương tự như kiểu danh sách(list) trong python, mảng numpy cũng có thể được cắt. Vì mảng có thể nhiều chiều, nên bạn phải chỉ việc cắt cho mỗi chiều của mảng.

In [20]:
# aivietnam.ai
import numpy as np
 
# Khởi tạo numpy array có shape = (2, 3) có giá trị như sau:
# [[ 1  2  3]
#  [ 5  6  7]

arr = np.array([[1,2,3], [5,6,7]])
print(arr)

[[1 2 3]
 [5 6 7]]


In [21]:
# aivietnam.ai
import numpy as np
 
# Khởi tạo numpy array có 
# shape=(2, 3) có giá trị như sau:
# [[ 1  2  3]
#  [ 5  6  7]
a_arr = np.array([[1,2,3], 
                  [5,6,7]])

# Sử dụng slicing để tạo mảng b_arr 
# bằng cách lấy tất cả các dòng và cột 1,2
# [[2 3]
#  [6 7]]
b_arr = a_arr[:, 1:3]
print('\nb_arr \n', b_arr)


b_arr 
 [[2 3]
 [6 7]]


In [22]:
# aivietnam.ai
import numpy as np
 
# Khởi tạo numpy array a_arr
a_arr = np.array([[1,2,3], 
                  [5,6,7]])
print(a_arr)

[[1 2 3]
 [5 6 7]]


In [23]:
b_arr = a_arr[:, 1:3]
print(b_arr)

[[2 3]
 [6 7]]


In [24]:
# aivietnam.ai
import numpy as np
 
# Khởi tạo numpy array a_arr
a_arr = np.array([[1,2,3], 
                  [5,6,7]])

# Sử dụng slicing để tạo mảng b_arr 
# bằng cách lấy tất cả các dòng và cột 1,2
b_arr = a_arr[:, 1:3]


print(b_arr)

[[2 3]
 [6 7]]


In [25]:
# aivietnam.ai
import numpy as np
 
# Khởi tạo numpy array a_arr
a_arr = np.array([[1,2,3], 
                  [5,6,7]])
print('a_arr \n', a_arr)

# Sử dụng slicing để tạo mảng b_arr
b_arr = a_arr[:, 1:3]
print('b_arr \n', b_arr)

print('before changing \n', a_arr[0, 1])
b_arr[0, 0] = 99 
print('after changing \n', a_arr[0, 1])

a_arr 
 [[1 2 3]
 [5 6 7]]
b_arr 
 [[2 3]
 [6 7]]
before changing 
 2
after changing 
 99


In [26]:
# aivietnam.ai
import numpy as np
 
# Tạo một numpy array có shape (3, 3) với giá trị như sau:
# [[ 1  2  3]
#  [ 5  6  7]
#  [ 9 10 11]]
arr = np.array([[1, 2, 3], 
                [5, 6, 7], 
                [9,10,11]])
 
# Hai cách truy cập dữ liệu ở dòng index=1
# cách 1: số chiều giảm
row_m1 = arr[1, :]  

# cách 2: số chiều được giữa nguyên
row_m2 = arr[1:2, :] 

print(row_m1, row_m1.shape)
print(row_m1, row_m2.shape)

[5 6 7] (3,)
[5 6 7] (1, 3)


In [27]:
# aivietnam.ai
import numpy as np
 
# Tạo một numpy array có shape (3, 3) với giá trị
arr = np.array([[1,2,3], 
                [5,6,7], 
                [9,10,11]])
 
# Hai cách truy cập dữ liệu ở cột index=1 của mảng
# cách 1: số chiều giảm
col_m1 = arr[:, 1]

# cách 2: số chiều được giữa nguyên
col_m2 = arr[:, 1:2]

print(col_m1, col_m1.shape)
print(col_m2, col_m2.shape)                            

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


### Integer array indexing:
    
Khi bạn truy xuất mảng dùng slicing, kết quả trả về sẽ là mảng con của mảng ban đầu, tuy nhiên sử dụng chỉ số mảng cho phép bạn xây dựng mảng tùy ý từ một mảng khác, ví dụ: 

In [28]:
# aivietnam.ai
import numpy as np

# tạo arr
arr = np.array([[1,2], 
                [3, 4], 
                [5, 6]])
 
# lấy giá trị vị trí (0,0), (1,1) và (2,0)
out1 = arr[[0, 1, 2], [0, 1, 0]]
print('out1:\n', out1)

# Có thể truy xuất tới 1 phần tử nhiều hơn 1 lần
out2 = arr[[0, 0], [1, 1]]
print('out2:\n', out2)

out1:
 [1 4 5]
out2:
 [2 2]


### Một mẹo hữu ích dùng chỉ số mảng để chọn và thay đổi phần tử từ mỗi hàng của ma trận

In [29]:
# aivietnam.ai
import numpy as np

# Tạo một mảng mới có shape=(4,3)
a_arr = np.array([[1,2,3], [5,6,7], [9,10,11], [13, 14, 15]])
print(a_arr)

# Tạo một mảng các chỉ số
b_arr = np.array([0, 2, 0, 1])

# Lấy 1 phần tử từ mỗi hàng của mảng a_arr dùng với chỉ số ở mảng b_arr

c_array = a_arr[np.arange(4), b_arr]

print(c_array)  # Prints "[ 1  7  9 14]"


[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
[ 1  7  9 14]


In [30]:
# aivietnam.ai
import numpy as np

# Tạo một mảng mới từ đó ta sẽ chọn các phần tử
a_arr = np.array([[1,2,3], [5,6,7], [9,10,11], [13, 14, 15]])

print(a_arr)    # prints "a_array([[ 1,2,3],
                #                [5,6,7],
                #                [ 9,10,11],
                #                [13, 14, 15]])"

# Tạo một mảng các chỉ số
b_arr = np.array([0, 2, 0, 1])

# Lấy 1 phần tử từ mỗi hàng của mảng a dùng với chỉ số ở mảng b
print(a_arr[np.arange(4), b_arr])  # Prints "[ 1  7  9 14]"

# Thay đổi một phẩn tử từ mỗi hàng của a dùng với chỉ số ở mảng b
a_arr[np.arange(4), b_arr] += 10

print(a_arr)    # prints "array([[11,  2,  3],
                #                [ 4,  5, 16],
                #                [17,  8,  9],
                #                [10, 21, 12]])

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
[ 1  7  9 14]
[[11  2  3]
 [ 5  6 17]
 [19 10 11]
 [13 24 15]]


### Boolean array indexing: 

In [31]:
# aivietnam.ai
import numpy as np

arr = np.array([[1,2], 
                [3, 4], 
                [5, 6]])
print(arr)

# Tìm các phần tử lớn hơn 2
bool_idx = (arr > 2)
print(bool_idx) 

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]


In [32]:
# aivietnam.ai
import numpy as np

a_arr = np.array([[1,2], [3, 4], [5, 6]])
print(a_arr)

# Tìm các phần tử lớn hơn 2;
# Trả về 1 mảng boolean có chiều như mảng a
# và giá trị tại mỗi phần tử là 
# True nếu phần tử của a tại đó > 2,
# False cho trường hợp ngược lại.
bool_idx = (a_arr > 2)
print('\nbool_idx\n', bool_idx)

# Chúng ta sử dụng boolean array indexing để xây dựng mảng 1 chiều 
# bao gồm các phần tử tương ứng với giá trị True của bool_idx

# Ví dụ ở đây in ra các giá trị của a_arr > 2 , sử dụng array bool_idx đã tạo
out = a_arr[bool_idx]
print('\nmethod 1\n', out)

# Một cách ngắn gọn hơn:
print('\nmethod 1\n', a_arr[a_arr > 2])

[[1 2]
 [3 4]
 [5 6]]

bool_idx
 [[False False]
 [ True  True]
 [ True  True]]

method 1
 [3 4 5 6]

method 1
 [3 4 5 6]


### Kiểu dữ liệu (Datatypes)


In [33]:
# aivietnam.ai
import numpy as np

# int32
arr1 = np.array([1, 2])
print(arr1.dtype)       

# float64
arr2 = np.array([1.0, 2.0])  
print(arr2.dtype)             

# int64
arr3 = np.array([1, 2], dtype=np.int64)  
print(arr3.dtype)                        

int32
float64
int64


In [34]:
# aivietnam.ai
import numpy as np

X = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])
v = np.array([1, 0, 1])

v = v.reshape((1,3))

print(X.shape)
print(v.shape)

(3, 3)
(1, 3)


In [35]:
Y = X + v 
print(Y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]


In [36]:
# aivietnam.ai
import numpy as np

X = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])
v = np.array([1, 0, 1])

v = v.reshape((3,1))

print(X.shape)
print(v.shape)

(3, 3)
(3, 1)


In [37]:
Y = X + v 
print(Y)

[[ 2  3  4]
 [ 4  5  6]
 [ 8  9 10]]
