In [39]:
# importing required packages
import numpy
import time


def multiplizeList(size=1000):
  # declaring lists
  list1 = list(range(size))
  list2 = list(range(size))

  # capturing time before the multiplication of Python lists
  initialTime = time.time()

  # multiplying elements of both the lists and stored in another list
  resultantList = [(a * b) for a, b in zip(list1, list2)]

  # calculating execution time
  print("Time taken by Lists to perform multiplication:",
    (time.time() - initialTime),
    "seconds")



def multiplizeArray(size=1000):
  # declaring arrays
  array1 = numpy.arange(size)
  array2 = numpy.arange(size)

  # capturing time before the multiplication of Numpy arrays
  initialTime = time.time()

# multiplying elements of both the Numpy arrays and stored in another Numpy array
  resultantArray = array1 * array2

# calculating execution time
  print("Time taken by NumPy Arrays to perform multiplication:",
    (time.time() - initialTime),
    "seconds")


In [41]:
def computeIoU(boxA, boxB):
	# determine the (x, y)-coordinates of the intersection rectangle
	xA = max(boxA[0], boxB[0])
	yA = max(boxA[1], boxB[1])
	xB = min(boxA[2], boxB[2])
	yB = min(boxA[3], boxB[3])

	interArea = max(0, xB - xA + 1) * max(0, yB - yA + 1)
	# print("interArea", interArea)

	# compute the area of both the prediction and ground-truth
	# rectangles
	boxAArea = (boxA[2] - boxA[0] + 1) * (boxA[3] - boxA[1] + 1)
	boxBArea = (boxB[2] - boxB[0] + 1) * (boxB[3] - boxB[1] + 1)
	# compute the intersection over union by taking the intersection
	# area and dividing it by the sum of prediction + ground-truth
	# areas - the interesection area
	iou = interArea / float(boxAArea + boxBArea - interArea)
	# return the intersection over union value
	return iou

In [48]:
# Example usage
boxes = []
for i in range(10000):
  boxes.append([i+1, i+1, i+1, i+1])

initialTime = time.time()

for i in range(1, len(boxes)):
  iou = computeIoU(boxes[0],boxes[i])
  # print("iou", iou)


# calculating execution time
print("Time taken by NumPy Arrays to perform multiplication:",
    (time.time() - initialTime),
    "seconds")

Time taken by NumPy Arrays to perform multiplication: 0.023508548736572266 seconds


In [49]:
# Array solution
initialTime = time.time()
boxes = np.array(boxes)
scores = np.array(scores)
# Coordinates of bounding boxes
x1 = boxes[:, 0]
y1 = boxes[:, 1]
x2 = boxes[:, 2]
y2 = boxes[:, 3]

# Compute the area of the bounding boxes
areas = (x2 - x1 + 1) * (y2 - y1 + 1)

# Compute the intersection areas
xx1 = np.maximum(x1[0], x1[1:])
yy1 = np.maximum(y1[0], y1[1:])
xx2 = np.minimum(x2[0], x2[1:])
yy2 = np.minimum(y2[0], y2[1:])

w = np.maximum(0, xx2 - xx1 + 1)
h = np.maximum(0, yy2 - yy1 + 1)

inter = w * h

# # Compute the IoU
iou = inter / (areas[0] + areas[1:] - inter)
# print(iou)

print("Time taken by NumPy Arrays to perform multiplication:",
    (time.time() - initialTime),
    "seconds")

Time taken by NumPy Arrays to perform multiplication: 0.008990049362182617 seconds


In [ ]:
multiplizeList(100000)
multiplizeArray(100000)

Time taken by Lists to perform multiplication: 0.010344743728637695 seconds
100000
Time taken by NumPy Arrays to perform multiplication: 0.0006392002105712891 seconds


In [35]:
# List solution
def compute_iou(box1, box2):
        x1_1, y1_1, x2_1, y2_1 = box1
        x1_2, y1_2, x2_2, y2_2 = box2

        # Compute the coordinates of the intersection rectangle
        xx1 = max(x1_1, x1_2)
        yy1 = max(y1_1, y1_2)
        xx2 = min(x2_1, x2_2)
        yy2 = min(y2_1, y2_2)

        # Compute the width and height of the intersection rectangle
        w = max(0, xx2 - xx1 + 1)
        h = max(0, yy2 - yy1 + 1)

        # Compute the area of the intersection rectangle
        inter_area = w * h

        # Compute the area of both bounding boxes
        box1_area = (x2_1 - x1_1 + 1) * (y2_1 - y1_1 + 1)
        box2_area = (x2_2 - x1_2 + 1) * (y2_2 - y1_2 + 1)

        # Compute the Intersection over Union (IoU)
        iou = inter_area / float(box1_area + box2_area - inter_area)

        return iou

# Refine for class
def non_max_suppression(boxes, scores, iou_threshold):


    # Sort the boxes by scores in descending order
    sorted_indices = sorted(range(len(scores)), key=lambda k: scores[k], reverse=True)

    keep = []  # List to store the indices of boxes to keep

    while sorted_indices:
        i = sorted_indices.pop(0)  # Index of the current highest score box
        keep.append(i)
        # print("sorted_indices", sorted_indices)
        filtered_indices = []
        for j in sorted_indices:
            iou = compute_iou(boxes[i], boxes[j])
            if iou <= iou_threshold:
                filtered_indices.append(j)

        sorted_indices = filtered_indices

    return keep

# Example usage
# boxes = [
#     [12, 84, 140, 212],
#     [24, 84, 152, 212],
#     [36, 84, 164, 212],
#     [12, 96, 140, 224],
#     [24, 96, 152, 224]
# ]

# scores = [0.3, 0.4, 0.5, 0.6, 0.7]
# iou_threshold = 0.3

boxes = np.array([
    [100, 100, 210, 210],
    [105, 105, 215, 215],
    [150, 150, 250, 250]
])

scores = np.array([0.9, 0.8, 0.7])
threshold = 0.5


kept_indices = non_max_suppression(boxes, scores, iou_threshold)
kept_boxes = [boxes[i] for i in kept_indices]

print("Kept indices:", kept_indices)
print("Kept boxes:", kept_boxes)


Kept indices: [0, 2]
Kept boxes: [array([100, 100, 210, 210]), array([150, 150, 250, 250])]


In [60]:
import numpy as np

def non_max_suppression(boxes, scores, threshold):
    """
    Perform non-maximum suppression.

    Parameters:
    boxes (numpy.ndarray): Array of bounding boxes, each defined by [x1, y1, x2, y2].
    scores (numpy.ndarray): Array of confidence scores for each bounding box.
    threshold (float): Overlap threshold for suppression.

    Returns:
    numpy.ndarray: Indices of bounding boxes to keep.
    """
    if len(boxes) == 0:
        return []

    # Coordinates of bounding boxes
    x1 = boxes[:, 0]
    y1 = boxes[:, 1]
    x2 = boxes[:, 2]
    y2 = boxes[:, 3]

    # Compute area of bounding boxes
    areas = (x2 - x1 + 1) * (y2 - y1 + 1)

    # Sort by scores
    order = scores.argsort()[::-1]

    keep = []
    while order.size > 0:
        i = order[0]
        keep.append(i)

        # Compute IoU (Intersection over Union)
        xx1 = np.maximum(x1[i], x1[order[1:]])
        yy1 = np.maximum(y1[i], y1[order[1:]])
        xx2 = np.minimum(x2[i], x2[order[1:]])
        yy2 = np.minimum(y2[i], y2[order[1:]])

        w = np.maximum(0, xx2 - xx1 + 1)
        h = np.maximum(0, yy2 - yy1 + 1)

        intersection = w * h
        iou = intersection / (areas[i] + areas[order[1:]] - intersection)

        # Suppress bounding boxes with IoU over the threshold
        inds = np.where(iou <= threshold)[0]
        order = order[inds + 1]

    return keep

# Example usage
boxes = np.array([
    [100, 100, 210, 210],
    [105, 105, 215, 215],
    [150, 150, 250, 250]
])

scores = np.array([0.9, 0.8, 0.7])
threshold = 0.5

keep_indices = non_max_suppression(boxes, scores, threshold)
kept_boxes = boxes[keep_indices]

print("Indices of boxes to keep:", keep_indices)
print("Boxes to keep:")
print(kept_boxes)


Indices of boxes to keep: [0, 2]
Boxes to keep:
[[100 100 210 210]
 [150 150 250 250]]


In [11]:
import numpy as np

original_array = np.arange(11)

original_array = original_array.reshape((3, 4))

print(original_array.shape)


(3, 4)


In [18]:
import numpy as np

# Create a 2D array
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Sum across columns
column_sum = np.sum(array, axis=0)

print("Array:")
print(array)
print("\nSum across columns:", column_sum)


Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Sum across columns: [12 15 18]


In [20]:
import numpy as np

# Create a 2D array
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

filtered_elements = array[(array > 2) & (array < 5)]

filtered_elements = filtered_elements[::-1]

print(filtered_elements)


[4 3]


In [19]:
import numpy as np

# Create a 2D array
original_array = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])

reshaped_array = original_array.reshape(-1)

print("Original array (2D):")
print(original_array)
print("\nReshaped array (1D):")
print(reshaped_array)


Original array (2D):
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Reshaped array (1D):
[1 2 3 4 5 6 7 8 9]


In [23]:
import numpy as np

# Create a 1D array
array1 = np.array([1, 2, 3])

# Create a 2D array
array2 = np.array([[4, 5, 6],
                   [7, 8, 9]])

result = array1 + array2

print(result)


[[ 5  7  9]
 [ 8 10 12]]


In [25]:
np.array([1, 2, 3]) + np.array([[1], [2], [3]])

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])