In [1]:
!gdown 10abEfTSrWVzR6D24mdhbwACf3LDYltY7

Downloading...
From: https://drive.google.com/uc?id=10abEfTSrWVzR6D24mdhbwACf3LDYltY7
To: /content/Fish.csv
100% 6.47k/6.47k [00:00<00:00, 15.9MB/s]


In [3]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

#1.Load Data

In [4]:
df = pd.read_csv('./Fish.csv')
df

,Species,Weight,VerticalLen,DiagonalLen,CrossLen,Height,Width
0,Bream,242.0,23.2,25.4,30.0,11.5200,4.0200
1,Bream,290.0,24.0,26.3,31.2,12.4800,4.3056
2,Bream,340.0,23.9,26.5,31.1,12.3778,4.6961
3,Bream,363.0,26.3,29.0,33.5,12.7300,4.4555
4,Bream,430.0,26.5,29.0,34.0,12.4440,5.1340
...,...,...,...,...,...,...,...
154,Smelt,12.2,11.5,12.2,13.4,2.0904,1.3936
155,Smelt,13.4,11.7,12.4,13.5,2.4300,1.2690
156,Smelt,12.2,12.1,13.0,13.8,2.2770,1.2558
157,Smelt,19.7,13.2,14.3,15.2,2.8728,2.0672


In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Species      159 non-null    object 
 1   Weight       159 non-null    float64
 2   VerticalLen  159 non-null    float64
 3   DiagonalLen  159 non-null    float64
 4   CrossLen     159 non-null    float64
 5   Height       159 non-null    float64
 6   Width        159 non-null    float64
dtypes: float64(6), object(1)
memory usage: 8.8+ KB


**One hot encoding**

In [8]:
df

,Species,Weight,VerticalLen,DiagonalLen,CrossLen,Height,Width
0,Bream,242.0,23.2,25.4,30.0,11.5200,4.0200
1,Bream,290.0,24.0,26.3,31.2,12.4800,4.3056
2,Bream,340.0,23.9,26.5,31.1,12.3778,4.6961
3,Bream,363.0,26.3,29.0,33.5,12.7300,4.4555
4,Bream,430.0,26.5,29.0,34.0,12.4440,5.1340
...,...,...,...,...,...,...,...
154,Smelt,12.2,11.5,12.2,13.4,2.0904,1.3936
155,Smelt,13.4,11.7,12.4,13.5,2.4300,1.2690
156,Smelt,12.2,12.1,13.0,13.8,2.2770,1.2558
157,Smelt,19.7,13.2,14.3,15.2,2.8728,2.0672


In [9]:
encode_species = pd.get_dummies(df.Species)
encode_species.head(5)

,Bream,Parkki,Perch,Pike,Roach,Smelt,Whitefish
0,True,False,False,False,False,False,False
1,True,False,False,False,False,False,False
2,True,False,False,False,False,False,False
3,True,False,False,False,False,False,False
4,True,False,False,False,False,False,False


**Label Encoding**

In [10]:
df["Species"] = df["Species"].astype('category')
label_ecnoding_species = df["Species"].cat.codes
label_ecnoding_species

,0
0,0
1,0
2,0
3,0
4,0
...,...
154,5
155,5
156,5
157,5


In [11]:
new_df = pd.concat([df, encode_species], axis='columns')
new_df

,Species,Weight,VerticalLen,DiagonalLen,CrossLen,Height,Width,Bream,Parkki,Perch,Pike,Roach,Smelt,Whitefish
0,Bream,242.0,23.2,25.4,30.0,11.5200,4.0200,True,False,False,False,False,False,False
1,Bream,290.0,24.0,26.3,31.2,12.4800,4.3056,True,False,False,False,False,False,False
2,Bream,340.0,23.9,26.5,31.1,12.3778,4.6961,True,False,False,False,False,False,False
3,Bream,363.0,26.3,29.0,33.5,12.7300,4.4555,True,False,False,False,False,False,False
4,Bream,430.0,26.5,29.0,34.0,12.4440,5.1340,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,Smelt,12.2,11.5,12.2,13.4,2.0904,1.3936,False,False,False,False,False,True,False
155,Smelt,13.4,11.7,12.4,13.5,2.4300,1.2690,False,False,False,False,False,True,False
156,Smelt,12.2,12.1,13.0,13.8,2.2770,1.2558,False,False,False,False,False,True,False
157,Smelt,19.7,13.2,14.3,15.2,2.8728,2.0672,False,False,False,False,False,True,False


In [12]:
X = new_df[[
    'VerticalLen', 'DiagonalLen', 'CrossLen', 'Height', 'Width',
    'Bream', 'Parkki', 'Perch', 'Pike', 'Roach', 'Smelt', 'Whitefish'
]]
y = new_df['Weight']

In [13]:
X = X.values
y = y.values

In [14]:
X

array([[23.2, 25.4, 30.0, ..., False, False, False],
       [24.0, 26.3, 31.2, ..., False, False, False],
       [23.9, 26.5, 31.1, ..., False, False, False],
       ...,
       [12.1, 13.0, 13.8, ..., False, True, False],
       [13.2, 14.3, 15.2, ..., False, True, False],
       [13.8, 15.0, 16.2, ..., False, True, False]], dtype=object)

In [15]:
X_data = np.hstack((np.ones((X.shape[0], 1)), X))
X_data

array([[1.0, 23.2, 25.4, ..., False, False, False],
       [1.0, 24.0, 26.3, ..., False, False, False],
       [1.0, 23.9, 26.5, ..., False, False, False],
       ...,
       [1.0, 12.1, 13.0, ..., False, True, False],
       [1.0, 13.2, 14.3, ..., False, True, False],
       [1.0, 13.8, 15.0, ..., False, True, False]], dtype=object)

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X_data, y, test_size=0.2, random_state=42)
print('X_train shape: ', X_train.shape)
print('X_test shape: ', X_test.shape)
print('y_train shape: ', y_train.shape)
print('y_train shape: ', y_test.shape)

X_train shape:  (127, 13)
X_test shape:  (32, 13)
y_train shape:  (127,)
y_train shape:  (32,)


#Linear Regression

In [17]:
def r2score(y_pred, y):
    rss = np.sum((y_pred - y) ** 2)
    tss = np.sum((y-y.mean()) ** 2)

    r2 = 1 - (rss / tss)
    return r2

In [18]:
class LinearRegression:
    def __init__(self, X_data, y_target, learning_rate=0.00001, num_epochs=10000):
        self.X_data = X_data
        self.y_target = y_target
        self.learning_rate = learning_rate
        self.num_epochs = num_epochs
        self.num_samples = self.X_data.shape[0]

        # Initial Coefficients
        self.theta = np.random.randn(self.X_data.shape[1])
        self.losses = []

    def compute_loss(self, y_pred, y_target):
        loss = (y_pred-y_target)*(y_pred-y_target)
        loss = np.mean(loss)
        return loss

    def predict(self, X_data):
        y_pred = X_data.dot(self.theta)
        return y_pred

    def fit(self):
        for epoch in range(self.num_epochs):
            # predict
            y_pred = self.predict(self.X_data)

            # compute loss
            loss = self.compute_loss(y_pred, self.y_target)
            self.losses.append(loss)

            # compute gradient
            k = 2*(y_pred-self.y_target)
            gradients = self.X_data.T.dot(k)/self.num_samples

            # update weight
            self.theta = self.theta - self.learning_rate*gradients

            print(f'Epoch: {epoch} - Loss: {loss}')

        return {
            'loss': sum(self.losses)/len(self.losses),
            'weight': self.theta
        }

In [19]:
linear_model = LinearRegression(X_train, y_train, learning_rate=0.00001, num_epochs=1000)
linear_model.fit()

Epoch: 0 - Loss: 226436.44783030206
Epoch: 1 - Loss: 206095.5832031268
Epoch: 2 - Loss: 188054.78354620922
Epoch: 3 - Loss: 172053.9633937767
Epoch: 4 - Loss: 157862.4470795469
Epoch: 5 - Loss: 145275.64315179436
Epoch: 6 - Loss: 134112.09483706168
Epoch: 7 - Loss: 124210.86402988921
Epoch: 8 - Loss: 115429.21109430096
Epoch: 9 - Loss: 107640.53702740379
Epoch: 10 - Loss: 100732.55831786695
Epoch: 11 - Loss: 94605.68818673713
Epoch: 12 - Loss: 89171.60087340449
Epoch: 13 - Loss: 84351.9582684398
Epoch: 14 - Loss: 80077.28053553517
Epoch: 15 - Loss: 76285.94444062826
Epoch: 16 - Loss: 72923.2949474078
Epoch: 17 - Loss: 69940.85727132803
Epoch: 18 - Loss: 67295.63803254049
Epoch: 19 - Loss: 64949.505432665595
Epoch: 20 - Loss: 62868.63951959015
Epoch: 21 - Loss: 61023.04461491603
Epoch: 22 - Loss: 59386.116874865904
Epoch: 23 - Loss: 57934.260750296955
Epoch: 24 - Loss: 56646.54881643492
Epoch: 25 - Loss: 55504.42006819224
Epoch: 26 - Loss: 54491.412331480205
Epoch: 27 - Loss: 53592.9249

{'loss': 48021.83670927769,
 'weight': array([-1.474197918528139, 5.62647066229165, 4.768973033779851,
        4.710261219264584, 1.8731797877089504, 0.2040158591695383,
        -1.237102503675169, 0.6609913245014487, 1.1258718747623089,
        0.4800350498295224, -1.5539439833383755, -0.15493256392669735,
        0.6648490658335175], dtype=object)}

In [20]:
preds = linear_model.predict(X_train)
r2score(preds, y_train)

0.6232921092937094

In [21]:
preds = linear_model.predict(X_test)
r2score(preds, y_test)

0.6420276046412661

#Polynomial Regression

##Simple Approach
**Form**
$(a+b)^2 => a^2 + b^2 + a + b + 1$

In [22]:
def create_polynomial_features(X, degree=2):
    """Creates the polynomial features
    Args:
        X: A array for the data.
        degree: A intege for the degree of
        the generated polynomial function.
    """
    X_mem = []
    for X_sub in X.T:
        X_sub = X_sub.T
        X_new = X_sub
        for d in range(2, degree+1):
            X_new = np.c_[X_new, np.power(X_sub, d)]
        X_mem.extend(X_new.T)
    return np.c_[X_mem].T

In [23]:
X_new = np.array([[1, 2], [3, 4]])
X_new

array([[1, 2],
       [3, 4]])

In [24]:
create_polynomial_features(X_new, degree=2)

array([[ 1,  1,  2,  4],
       [ 3,  9,  4, 16]])

In [25]:
create_polynomial_features(X_new, degree=3)

array([[ 1,  1,  1,  2,  4,  8],
       [ 3,  9, 27,  4, 16, 64]])

In [26]:
X_poly = create_polynomial_features(X, degree=2)
X_poly

array([[23.2, 538.24, 25.4, ..., 0, False, 0],
       [24.0, 576.0, 26.3, ..., 0, False, 0],
       [23.9, 571.2099999999999, 26.5, ..., 0, False, 0],
       ...,
       [12.1, 146.41, 13.0, ..., 1, False, 0],
       [13.2, 174.23999999999998, 14.3, ..., 1, False, 0],
       [13.8, 190.44000000000003, 15.0, ..., 1, False, 0]], dtype=object)

In [27]:
X_poly.shape

(159, 24)

In [28]:
X_data = np.hstack((np.ones((X_poly.shape[0], 1)), X_poly))
X_data

array([[1.0, 23.2, 538.24, ..., 0, False, 0],
       [1.0, 24.0, 576.0, ..., 0, False, 0],
       [1.0, 23.9, 571.2099999999999, ..., 0, False, 0],
       ...,
       [1.0, 12.1, 146.41, ..., 1, False, 0],
       [1.0, 13.2, 174.23999999999998, ..., 1, False, 0],
       [1.0, 13.8, 190.44000000000003, ..., 1, False, 0]], dtype=object)

In [29]:
X_data.shape, y.shape

((159, 25), (159,))

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X_data, y, test_size=0.2, random_state=42)
print('X_train shape: ', X_train.shape)
print('X_test shape: ', X_test.shape)
print('y_train shape: ', y_train.shape)
print('y_train shape: ', y_test.shape)

X_train shape:  (127, 25)
X_test shape:  (32, 25)
y_train shape:  (127,)
y_train shape:  (32,)


In [31]:
poly_model = LinearRegression(X_train, y_train, learning_rate=0.0000001, num_epochs=100000)
poly_model.fit()

Streaming output truncated to the last 5000 lines.
Epoch: 95000 - Loss: 3948.3312979619386
Epoch: 95001 - Loss: 3948.3213620584634
Epoch: 95002 - Loss: 3948.311426286392
Epoch: 95003 - Loss: 3948.301490645725
Epoch: 95004 - Loss: 3948.291555136454
Epoch: 95005 - Loss: 3948.281619758583
Epoch: 95006 - Loss: 3948.271684512112
Epoch: 95007 - Loss: 3948.261749397023
Epoch: 95008 - Loss: 3948.2518144133296
Epoch: 95009 - Loss: 3948.241879561024
Epoch: 95010 - Loss: 3948.231944840109
Epoch: 95011 - Loss: 3948.2220102505653
Epoch: 95012 - Loss: 3948.212075792414
Epoch: 95013 - Loss: 3948.202141465635
Epoch: 95014 - Loss: 3948.1922072702378
Epoch: 95015 - Loss: 3948.182273206212
Epoch: 95016 - Loss: 3948.172339273563
Epoch: 95017 - Loss: 3948.16240547228
Epoch: 95018 - Loss: 3948.1524718023657
Epoch: 95019 - Loss: 3948.1425382638217
Epoch: 95020 - Loss: 3948.132604856632
Epoch: 95021 - Loss: 3948.1226715808098
Epoch: 95022 - Loss: 3948.112738436344
Epoch: 95023 - Loss: 3948.1028054232356
Epoch

{'loss': 5440.416873315407,
 'weight': array([-1.186024227732807, -0.10625703399013225, -0.04161137893238147,
        -4.653702364805961, 1.1863107327078892, -3.5619985367762474,
        -0.6207557436006802, -0.6689185458062696, 1.947530084586497,
        -0.5686950910991957, 3.813984144585377, 0.8752262580394873,
        -2.7287508200363035, 0.4378940179478794, 1.1457152589350312,
        1.4249184692563206, 0.32422072875766383, -0.3134837200595102,
        -0.6541526454339001, -0.4881218419800449, -0.9384350478054749,
        0.486971417882043, -2.412084122337565, 0.740066233431221,
        -0.538389677544446], dtype=object)}

In [32]:
preds = poly_model.predict(X_train)
r2score(preds, y_train)

0.9682721437781945

In [33]:
preds = poly_model.predict(X_test)
r2score(preds, y_test)

0.9721394733658284

## **Sklearn**

In [36]:
X.shape

(159, 12)

In [37]:
y.shape

(159,)

In [38]:
from sklearn.preprocessing import PolynomialFeatures

In [39]:
poly_features = PolynomialFeatures(degree=2)

In [41]:
X_data = poly_features.fit_transform(X)
X_data

array([[ 1. , 23.2, 25.4, ...,  0. ,  0. ,  0. ],
       [ 1. , 24. , 26.3, ...,  0. ,  0. ,  0. ],
       [ 1. , 23.9, 26.5, ...,  0. ,  0. ,  0. ],
       ...,
       [ 1. , 12.1, 13. , ...,  1. ,  0. ,  0. ],
       [ 1. , 13.2, 14.3, ...,  1. ,  0. ,  0. ],
       [ 1. , 13.8, 15. , ...,  1. ,  0. ,  0. ]])

In [42]:
X_data.shape

(159, 91)

In [43]:
X_train, X_test, y_train, y_test = train_test_split(X_data, y, test_size=0.2, random_state=42)
print('X_train shape: ', X_train.shape)
print('X_test shape: ', X_test.shape)
print('y_train shape: ', y_train.shape)
print('y_train shape: ', y_test.shape)

X_train shape:  (127, 91)
X_test shape:  (32, 91)
y_train shape:  (127,)
y_train shape:  (32,)


In [45]:
poly_model = LinearRegression(X_train, y_train, learning_rate=0.0000001, num_epochs=100000)
poly_model.fit()

Streaming output truncated to the last 5000 lines.
Epoch: 95000 - Loss: 2552.734246503757
Epoch: 95001 - Loss: 2552.7272358010855
Epoch: 95002 - Loss: 2552.7202252500197
Epoch: 95003 - Loss: 2552.7132148505802
Epoch: 95004 - Loss: 2552.706204602776
Epoch: 95005 - Loss: 2552.699194506571
Epoch: 95006 - Loss: 2552.6921845619763
Epoch: 95007 - Loss: 2552.685174768977
Epoch: 95008 - Loss: 2552.6781651275764
Epoch: 95009 - Loss: 2552.671155637786
Epoch: 95010 - Loss: 2552.6641462995767
Epoch: 95011 - Loss: 2552.6571371129644
Epoch: 95012 - Loss: 2552.650128077929
Epoch: 95013 - Loss: 2552.6431191944735
Epoch: 95014 - Loss: 2552.6361104625926
Epoch: 95015 - Loss: 2552.629101882284
Epoch: 95016 - Loss: 2552.6220934535413
Epoch: 95017 - Loss: 2552.615085176357
Epoch: 95018 - Loss: 2552.608077050732
Epoch: 95019 - Loss: 2552.6010690766684
Epoch: 95020 - Loss: 2552.594061254154
Epoch: 95021 - Loss: 2552.5870535831828
Epoch: 95022 - Loss: 2552.580046063754
Epoch: 95023 - Loss: 2552.5730386958653


{'loss': 3853.4392716049415,
 'weight': array([-4.19374816e-01, -3.01244918e+00, -4.21594840e-01, -5.03198016e+00,
        -7.59860511e-01, -3.26200559e-01,  6.99057114e-01, -1.35913415e+00,
        -2.07706513e+00, -5.03498673e-01,  1.34311737e+00, -2.48102339e-01,
        -2.06675791e-01, -1.91260830e-01,  5.77245091e-01,  2.58276894e-02,
        -6.77741180e-01,  6.03289986e-01,  6.22696077e-01, -8.18350541e-01,
         2.58483671e-01, -1.07240346e+00, -7.37143762e-02,  9.71759404e-01,
         1.16020969e+00, -4.95725003e-01,  9.37019885e-01,  2.28921746e-01,
         1.10810622e-01, -2.50442086e-01, -7.79763840e-01, -1.06926007e+00,
        -2.36921843e+00, -1.70730490e+00, -1.58985507e+00,  2.56164810e-01,
        -3.86633206e-01,  4.31087025e-01,  3.68813026e-01, -3.03464641e+00,
        -3.95584467e-01, -7.65253543e-01, -1.78648164e+00, -5.33296867e-01,
         3.47014462e-01, -1.45918260e+00,  6.69481607e-01,  7.10532099e-01,
        -3.77801282e-01,  5.00357161e-01,  4.0785

In [46]:
preds = poly_model.predict(X_train)
r2score(preds, y_train)

0.9795043552105771